version: '3'

services:

  redis-master:
    container_name: redis-master
    image: redis
    volumes:
      - "./data/redis-master:/data"
    ports:
      - "7000:6379"

  redis-slave:
    container_name: redis-slave
    image: redis
    command: redis-server --slaveof redis-master 6379
    volumes:
      - "../data/redis-slave:/data"
    links:
      - redis-master
    ports:
      - "7001:6379"

