version: '2'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      "discovery.type": "single-node"
    ports:
      - 9300:9300
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    depends_on:
      - es
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: "http://es:9200"
