version: "3.9"
services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./data:/notebooks
      - ./config:/root/.jupyter

    environment:
      JUPYTER_ENABLE_LAB: "yes"


