version: "3.9"
services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./data:/notebooks
      - ./jupyter-lab.vimrc:/root/.jupyter/lab/user-settings/jupyterlab-vimrc/vimrc.jupyterlab-settings
    environment:
      JUPYTER_ENABLE_LAB: "yes"


